### ISSUE TITLE
instructions to build this monitor

### ISSUE THREAD

**Issue by bodo69** [tcater/ESP8266-Water-Alarm#1]
Hi sir,

I like a lot this water alarm and i am wondering if you can describe how this should be set up.
the firmware part should be on esp and the php part should be on  a device like raspberry pi.
those two devices should communicate between them or ....
I wish you a happy new year!

**Comment by tcater** [comment]
I never did get that design working properly. I had a lot of problems with
power and detecting the water as the voltage changed.

What I did end up doing is getting a smoke detector and connected two wires
to the test button. The alarm that I used has a light that turns on when
the alarm goes off
<https://www.homedepot.ca/en/home/p.battery-operated-safety-light-smoke-alarm-with-hush-feature.1000416674.html>.
I removed the power regulator and LED and put in my own regulator and an
ESP8266 in it's place. Because there is no power to the LED circuit unless
the alarm is active there is no drain on the battery plus the smoke alarm
has a built in chirp when the battery does get low. The circuit is very
simple no need for a PCB. There are two different versions in the photos
below, the one with the connector on the side is a smoke detector / water
detector, the other one is just a smoke detector.
![img_20151130_145058](https://cloud.githubusercontent.com/assets/1025732/21508936/d4fa7176-cc52-11e6-81dc-50a217654de7.jpg)
![img_20160229_145715](https://cloud.githubusercontent.com/assets/1025732/21508934/d4fa2bee-cc52-11e6-8927-b59093c38614.jpg)
![img_20160229_145734](https://cloud.githubusercontent.com/assets/1025732/21508935/d4fa5740-cc52-11e6-9d2d-4966767ed752.jpg)
![img_20160229_150607](https://cloud.githubusercontent.com/assets/1025732/21508937/d4fea17e-cc52-11e6-839a-952ac9cb9b35.jpg)

When the ESP wakes up it does a http call to a php page hosted on a
raspberry pi then sleeps for a set amount of time, The PHP takes variables
that are passed in the url and sends a notification email. I use the same
code for my garage door sensor
<https://github.com/tcater/ESP8266-Garage-door-Sensor> but it doesn't send
an email it just keeps a log of the state of the door
http://www.tristancater.com/iot/john/

If you are interested in any other specifics let me know I can dig out the
code, as simple as it is, and upload it to github.

Tristan




---
Tristan Cater
519-851-3377
